<?php
namespace ExportData;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-24 at 16:16:05.
 */
class BaseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Base
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Base;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
