<?php
namespace ExportData;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-24 at 16:16:05.
 */
class OpenDocTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var OpenDoc
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new OpenDoc;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ExportData\OpenDoc::setXsltSource
     * @todo   Implement testSetXsltSource().
     */
    public function testSetXsltSource()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ExportData\OpenDoc::setDocTemplate
     * @todo   Implement testSetDocTemplate().
     */
    public function testSetDocTemplate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ExportData\OpenDoc::setImageSource
     * @todo   Implement testSetImageSource().
     */
    public function testSetImageSource()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ExportData\OpenDoc::setImageColumn
     * @todo   Implement testSetImageColumn().
     */
    public function testSetImageColumn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ExportData\OpenDoc::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ExportData\OpenDoc::__get
     * @todo   Implement test__get().
     */
    public function test__get()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
